### ISSUE TITLE
Connects in windows, issues during capture after "Ready"

### ISSUE THREAD

**Issue by electroncraz** [JohnDMcMaster/gxs700#13]
Setup: Windows 10, Asus Laptop
Environment: Pycharm 2023 1.2, Python3, all python dependencies installed, specifically 'libusb' 1.0.27 and 'libusb1' 3.1.0
Windows Driver: Using 'Zadig' set Driver to WinUSB (v6.1.7600.16385), also attempted libusb-win32(v1.2.7.3) and libusbK(v3.1.0.0)
Dongle: Its the ebay $70 black dexis.

Running Dump-dev runs great and returns the following,

```
"C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\Scripts\python.exe" "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\dump_dev.py" 
Waiting for device to come up


Found device (post-FW): Gendex GXS700LG (post enumeration)
Bus 001 Device 010: ID 5328:2030
Up after 1.8 sec
Init state: 1
S/N (flash): 103831081
S/N (EEPROM): None
WARNING: S/N mismatch
  S/N guess: black Dexis (size 2)
Writing to dump/103831081

Versions
MCU:     0.5.10
FPGA:    0.3.6
FGPA WG: 0.4.5

FPGA signature: 0x1234
State: 1
Error: 0
Trigger params: b'000301f4'
Int time: 700
Img ctr: b'7e00000017000000'
Sensor dimensions: 1344w x 1850h

Dumping RAM
Dumping EEPROM
Dumping flash
Dumping register space

Process finished with exit code 0
```

Problem lies with capturing, constantly getting libusb issues. Printout of main.py with arg --force-trig below, 

```
"C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\Scripts\python.exe" "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\main.py" --force-trig 
Preparing capture
Waiting for device to come up


Found device (post-FW): Gendex GXS700LG (post enumeration)
Bus 001 Device 012: ID 5328:2030
Up after 1.8 sec
Init state: 1
Init state: 1
Forcing trigger
New state 2 (scan 0)
scan 0 (state 2)
New state 4 (scan 574)
scan 1000 (state 4)
scan 2000 (state 4)
scan 3000 (state 4)
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\main.py", line 95, in <module>
    main()
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\main.py", line 68, in main
    raw_main.run(
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\gxs700\raw_main.py", line 63, in run
    gxs.cap_binv(imgn, cb, force_trig=force_trig, xr=xr)
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\gxs700\usbint.py", line 877, in cap_binv
    imgb = self._cap_bin(scan_cb=scan_cb, force_trig=force_trig, xr=xr)
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\gxs700\usbint.py", line 856, in _cap_bin
    return self._cap_frame()
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\gxs700\usbint.py", line 746, in _cap_frame
    ret = self._cap_frame_bulk()
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\gxs700\usbint.py", line 781, in _cap_frame_bulk
    trans.submit()
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\lib\site-packages\usb1\__init__.py", line 747, in submit
    raiseUSBError(result)
  File "C:\Users\Owner\Documents\PyCharmProjects\GSX700 XRAY Imager\lib\site-packages\usb1\__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorNotFound: LIBUSB_ERROR_NOT_FOUND [-5]
New state 8 (scan 3778)
Ready (state 8)

Process finished with exit code 1
```

**Comment by electroncraz** [comment]
Searching LIBUSB_ERROR_NOT_FOUND [-5] for libusb and windows brings up a possible fix?

see post [https://github.com/libusb/libusb/issues/1307](url)

> Although this issue affects the composite devices, it may not be duplicate of the #1238.
> 
> Digging around this issue I found out, the libusb is able to open any WinUsb interface of the composite device only if the device driver provides GUID. This also works with the automatic driver installation (WCID) if the device implements "Extended Properties OS Feature Descriptor" with one GUID. If the device reports more GUIDs, opening the device fails with the error LIBUSB_ERROR_NOT_FOUND (-5).
> 
> The issue seems to be in reading the multiple GUIDs in the winusb_get_device_list() function. Each GUID is 39 bytes long, storing two GUIDs require at least 79 bytes. But the internal buffer is only 40 bytes long. After fixing that, I was able to open the device.

**Comment by electroncraz** [comment]
Made a breakthrough just now. I'm using a raspberry pi to run linux natively with PyCharm. Pycharm MUST have sudo privileges to access USB otherwise the libusb does not allow opening (and throws this exception). 

`sudo ./pycharm.sh`

Hurray!  Finally got an image captured with --force-trig!

So now, question is how to run it in elevated privileges in windows version of libusb and not get this libusb error..

**Comment by JohnDMcMaster** [comment]
Hi there! Glad to hear you got it working.

Linux: if you install the udev rules and plug in (see README) you should not need to sudo. But let me know if this doesn't work for you

Windows: I don't test / support this, but happy to add info to the README etc if you have more info

**Comment by electroncraz** [comment]
I figured running on the Pi for now. I did some exposures (manual xray emission via switch, it is known working good) and can't seem to get an image. One image is all white, the other black and then the _e image is a white noise image. The image below was produced while running main.py. The object being xray'd is a printed circuit board.


![2024-04-10_13_e](https://github.com/JohnDMcMaster/gxs700/assets/166229663/bec4a142-24d8-4c41-b2dc-76a23cc7612f)


I noticed in the Wiki there is a capture.py but it is not in github. Also regardless of --force-trig argument it still triggers anyways. Perhaps it is a hardware issue? The lines at the top of the image seem to differ with the gaussian white noise in the rest of the image.

**Comment by JohnDMcMaster** [comment]
Looks like a broken sensor. Is this one of those eBay $60 ones? I've never heard of one of those working

**Comment by electroncraz** [comment]
Its the cheap ebay one. I think the bonding wires could be the cause of the white noise? It does not change if zapped in xrays or not, so it doesn't behave like a floating sampling circuit. Any chance the firmware is damaged/can be re-programmed? Dump-Dev seemed to generate files with hex data in it (although it is "mostly" full of blank "0xFF" data ).

**Comment by JohnDMcMaster** [comment]
Ah well dump dev only accesses the flash, while the sensor is a separate wire bonded chip. Yes, a significant number of these have damaged bond wires after fluid ingress due to biting cracking the case + spit ingress.

In any case it sounds like you have a working software configuration so I'm going to close this ticket. Unfortunately I'm not able to assist further to troubleshoot your sensor.

**Comment by electroncraz** [comment]
Yep. I think the gxs700 codebase is good, with the exception of the auto-trigging which may be a defect in my unit? On the windows side there's issues with libusb and sudo privileges access, which is an external problem with this codebase.

Has anyone attempted repair to those bond wires? Is it even possible? I'm debating whether to just return the unit or DIY those bond wires.
